//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPI.Tester.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMeassage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMeassage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPI.Tester.Gui.ResourceMeassage", typeof(ResourceMeassage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Check Sourecemeter is power on ?
        ///2. Sourcemeter connect  IPC cable is Ready ?.
        /// </summary>
        internal static string ERR_00307 {
            get {
                return ResourceManager.GetString("ERR_00307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Reset Gain / Offset Table?.
        /// </summary>
        internal static string MSG_001 {
            get {
                return ResourceManager.GetString("MSG_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Reset Coef. Table?&quot;.
        /// </summary>
        internal static string MSG_002 {
            get {
                return ResourceManager.GetString("MSG_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Reset Chuck Gain / Offset Table?.
        /// </summary>
        internal static string MSG_003 {
            get {
                return ResourceManager.GetString("MSG_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result Output File Exist, Would you overwrite it?.
        /// </summary>
        internal static string MSG_004 {
            get {
                return ResourceManager.GetString("MSG_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting , Please Restart the application？.
        /// </summary>
        internal static string MSG_005 {
            get {
                return ResourceManager.GetString("MSG_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; Log Out ?.
        /// </summary>
        internal static string MSG_006 {
            get {
                return ResourceManager.GetString("MSG_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would  you want to reset system state ?.
        /// </summary>
        internal static string MSG_007 {
            get {
                return ResourceManager.GetString("MSG_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Data Format Error !!.
        /// </summary>
        internal static string MSG_008 {
            get {
                return ResourceManager.GetString("MSG_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Delete Task Sheet ?.
        /// </summary>
        internal static string MSG_009 {
            get {
                return ResourceManager.GetString("MSG_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Insert Test  Item ?.
        /// </summary>
        internal static string MSG_010 {
            get {
                return ResourceManager.GetString("MSG_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Delete Test  Item ?.
        /// </summary>
        internal static string MSG_011 {
            get {
                return ResourceManager.GetString("MSG_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete too much compared chips，Please Confirm Test Data is Correct ？.
        /// </summary>
        internal static string MSG_101 {
            get {
                return ResourceManager.GetString("MSG_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Confirm Replace System Gain / Offset Coeff ?.
        /// </summary>
        internal static string MSG_102 {
            get {
                return ResourceManager.GetString("MSG_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Replace System Coeff  Table?.
        /// </summary>
        internal static string MSG_103 {
            get {
                return ResourceManager.GetString("MSG_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine This Item Gain / Offset Coeff ?  .
        /// </summary>
        internal static string MSG_104 {
            get {
                return ResourceManager.GetString("MSG_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine All  Item Gain / Offset Coeff ?.
        /// </summary>
        internal static string MSG_105 {
            get {
                return ResourceManager.GetString("MSG_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you Reset Chuck Gain / Offset Table?.
        /// </summary>
        internal static string MSG_106 {
            get {
                return ResourceManager.GetString("MSG_106", resourceCulture);
            }
        }
    }
}
