//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPI.Tester.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceErr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPI.Tester.Gui.ResourceErr", typeof(ResourceErr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined the error code.
        /// </summary>
        internal static string ERR_00001 {
            get {
                return ResourceManager.GetString("ERR_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Initialization fail.
        /// </summary>
        internal static string ERR_00201 {
            get {
                return ResourceManager.GetString("ERR_00201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Serial number (S/N) error.
        /// </summary>
        internal static string ERR_00202 {
            get {
                return ResourceManager.GetString("ERR_00202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere, Serial number (S/N) error.
        /// </summary>
        internal static string ERR_00203 {
            get {
                return ResourceManager.GetString("ERR_00203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, No set parameters setting data.
        /// </summary>
        internal static string ERR_00204 {
            get {
                return ResourceManager.GetString("ERR_00204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS Spectrometer auto count setting error.
        /// </summary>
        internal static string ERR_00205 {
            get {
                return ResourceManager.GetString("ERR_00205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS Spectrometer re-try connect fail.
        /// </summary>
        internal static string ERR_00206 {
            get {
                return ResourceManager.GetString("ERR_00206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS Calculation fail.
        /// </summary>
        internal static string ERR_00207 {
            get {
                return ResourceManager.GetString("ERR_00207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS Spectrometer trigger error.
        /// </summary>
        internal static string ERR_00208 {
            get {
                return ResourceManager.GetString("ERR_00208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS Get Intensity fail.
        /// </summary>
        internal static string ERR_00209 {
            get {
                return ResourceManager.GetString("ERR_00209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRS_.
        /// </summary>
        internal static string ERR_00210 {
            get {
                return ResourceManager.GetString("ERR_00210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Get wavelength fail.
        /// </summary>
        internal static string ERR_00211 {
            get {
                return ResourceManager.GetString("ERR_00211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Get the dark data fail.
        /// </summary>
        internal static string ERR_00212 {
            get {
                return ResourceManager.GetString("ERR_00212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Load calibration file fail.
        /// </summary>
        internal static string ERR_00213 {
            get {
                return ResourceManager.GetString("ERR_00213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Calculation function initialization fail.
        /// </summary>
        internal static string ERR_00214 {
            get {
                return ResourceManager.GetString("ERR_00214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrometer, Connect Error.
        /// </summary>
        internal static string ERR_00215 {
            get {
                return ResourceManager.GetString("ERR_00215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Initialization fail.
        /// </summary>
        internal static string ERR_00301 {
            get {
                return ResourceManager.GetString("ERR_00301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter,  No set parameter setting data.
        /// </summary>
        internal static string ERR_00302 {
            get {
                return ResourceManager.GetString("ERR_00302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, meter ouput data index error.
        /// </summary>
        internal static string ERR_00303 {
            get {
                return ResourceManager.GetString("ERR_00303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Sweep setting data error.
        /// </summary>
        internal static string ERR_00304 {
            get {
                return ResourceManager.GetString("ERR_00304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, PMU index setting error.
        /// </summary>
        internal static string ERR_00305 {
            get {
                return ResourceManager.GetString("ERR_00305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Force ouptut singal (current / voltage) control fail.
        /// </summary>
        internal static string ERR_00306 {
            get {
                return ResourceManager.GetString("ERR_00306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Hardware device error.
        /// </summary>
        internal static string ERR_00307 {
            get {
                return ResourceManager.GetString("ERR_00307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Disconnect.
        /// </summary>
        internal static string ERR_00317 {
            get {
                return ResourceManager.GetString("ERR_00317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Acquire Data Timeout.
        /// </summary>
        internal static string ERR_00318 {
            get {
                return ResourceManager.GetString("ERR_00318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcemeter, Not Detected the Detector Channel.
        /// </summary>
        internal static string ERR_00320 {
            get {
                return ResourceManager.GetString("ERR_00320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch System, Initialization fail.
        /// </summary>
        internal static string ERR_00501 {
            get {
                return ResourceManager.GetString("ERR_00501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchSystem, No Switch Card in Slot.
        /// </summary>
        internal static string ERR_00502 {
            get {
                return ResourceManager.GetString("ERR_00502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchSystem, Config Data Missing.
        /// </summary>
        internal static string ERR_00503 {
            get {
                return ResourceManager.GetString("ERR_00503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchSystem, Channel Setting Error.
        /// </summary>
        internal static string ERR_00504 {
            get {
                return ResourceManager.GetString("ERR_00504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAQ, Initialization fail.
        /// </summary>
        internal static string ERR_00601 {
            get {
                return ResourceManager.GetString("ERR_00601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAQ, Acquire Data Timeout.
        /// </summary>
        internal static string ERR_00602 {
            get {
                return ResourceManager.GetString("ERR_00602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCR meter, Initialization fail.
        /// </summary>
        internal static string ERR_00701 {
            get {
                return ResourceManager.GetString("ERR_00701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System,  Not ready for testing.
        /// </summary>
        internal static string ERR_01001 {
            get {
                return ResourceManager.GetString("ERR_01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System, Not finish this one data saving.
        /// </summary>
        internal static string ERR_01002 {
            get {
                return ResourceManager.GetString("ERR_01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System, Filter wheel setting error.
        /// </summary>
        internal static string ERR_01003 {
            get {
                return ResourceManager.GetString("ERR_01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System, DUT Channel Config Not Match.
        /// </summary>
        internal static string ERR_01101 {
            get {
                return ResourceManager.GetString("ERR_01101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR_10001 {
            get {
                return ResourceManager.GetString("ERR_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR_10002 {
            get {
                return ResourceManager.GetString("ERR_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load UI setting file fail.
        /// </summary>
        internal static string ERR_10003 {
            get {
                return ResourceManager.GetString("ERR_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load tester system setting file fail.
        /// </summary>
        internal static string ERR_10004 {
            get {
                return ResourceManager.GetString("ERR_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load product setting file fail.
        /// </summary>
        internal static string ERR_10005 {
            get {
                return ResourceManager.GetString("ERR_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load bin setting file fail.
        /// </summary>
        internal static string ERR_10006 {
            get {
                return ResourceManager.GetString("ERR_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user defined data file fail.
        /// </summary>
        internal static string ERR_10007 {
            get {
                return ResourceManager.GetString("ERR_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load task sheet file fail.
        /// </summary>
        internal static string ERR_10008 {
            get {
                return ResourceManager.GetString("ERR_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset user defined data fail.
        /// </summary>
        internal static string ERR_10009 {
            get {
                return ResourceManager.GetString("ERR_10009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t match the selected format of user data .
        /// </summary>
        internal static string ERR_10010 {
            get {
                return ResourceManager.GetString("ERR_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task sheet file name has exited.
        /// </summary>
        internal static string ERR_10011 {
            get {
                return ResourceManager.GetString("ERR_10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result output file name has exited.
        /// </summary>
        internal static string ERR_10012 {
            get {
                return ResourceManager.GetString("ERR_10012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine configure setting error.
        /// </summary>
        internal static string ERR_10013 {
            get {
                return ResourceManager.GetString("ERR_10013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching device specification in machine config.
        /// </summary>
        internal static string ERR_10014 {
            get {
                return ResourceManager.GetString("ERR_10014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR_10015 {
            get {
                return ResourceManager.GetString("ERR_10015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected save LOP  item is not match.
        /// </summary>
        internal static string ERR_10016 {
            get {
                return ResourceManager.GetString("ERR_10016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file fail.
        /// </summary>
        internal static string ERR_10017 {
            get {
                return ResourceManager.GetString("ERR_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file, The path setting fail.
        /// </summary>
        internal static string ERR_10018 {
            get {
                return ResourceManager.GetString("ERR_10018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No save file name.
        /// </summary>
        internal static string ERR_10019 {
            get {
                return ResourceManager.GetString("ERR_10019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Can&apos;t find the title in the file.
        /// </summary>
        internal static string ERR_10020 {
            get {
                return ResourceManager.GetString("ERR_10020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Can&apos;t find the bin column in the file.
        /// </summary>
        internal static string ERR_10021 {
            get {
                return ResourceManager.GetString("ERR_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Transfer fail.
        /// </summary>
        internal static string ERR_10022 {
            get {
                return ResourceManager.GetString("ERR_10022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Target path setting fail.
        /// </summary>
        internal static string ERR_10023 {
            get {
                return ResourceManager.GetString("ERR_10023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Load tested data fail.
        /// </summary>
        internal static string ERR_10024 {
            get {
                return ResourceManager.GetString("ERR_10024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTransfer, Save transfered data fail.
        /// </summary>
        internal static string ERR_10025 {
            get {
                return ResourceManager.GetString("ERR_10025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR_10026 {
            get {
                return ResourceManager.GetString("ERR_10026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR_10027 {
            get {
                return ResourceManager.GetString("ERR_10027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Table, Selected Items Error.
        /// </summary>
        internal static string ERR_10031 {
            get {
                return ResourceManager.GetString("ERR_10031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Get Enough Memory For Saving Reports..
        /// </summary>
        internal static string ERR_10040 {
            get {
                return ResourceManager.GetString("ERR_10040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Mode Error.
        /// </summary>
        internal static string ERR_10042 {
            get {
                return ResourceManager.GetString("ERR_10042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Extend Filename Repeat.
        /// </summary>
        internal static string ERR_10043 {
            get {
                return ResourceManager.GetString("ERR_10043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP Connect Timeout.
        /// </summary>
        internal static string ERR_10044 {
            get {
                return ResourceManager.GetString("ERR_10044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Channel Data is not match to H/W Channel Setting.
        /// </summary>
        internal static string ERR_10060 {
            get {
                return ResourceManager.GetString("ERR_10060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Load mk file fail at fully auto mode.
        /// </summary>
        internal static string ERR_10101 {
            get {
                return ResourceManager.GetString("ERR_10101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Content of mk file is not find.
        /// </summary>
        internal static string ERR_10102 {
            get {
                return ResourceManager.GetString("ERR_10102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Lot Number is not matching.
        /// </summary>
        internal static string ERR_10103 {
            get {
                return ResourceManager.GetString("ERR_10103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Calibration parameters is not matching.
        /// </summary>
        internal static string ERR_10104 {
            get {
                return ResourceManager.GetString("ERR_10104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Load mk file fail at sampling mode.
        /// </summary>
        internal static string ERR_10105 {
            get {
                return ResourceManager.GetString("ERR_10105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WM, Wafer number is not matching.
        /// </summary>
        internal static string ERR_10106 {
            get {
                return ResourceManager.GetString("ERR_10106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools, Load Standard File Fail.
        /// </summary>
        internal static string ERR_20001 {
            get {
                return ResourceManager.GetString("ERR_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools,Load Measure File Fail.
        /// </summary>
        internal static string ERR_20002 {
            get {
                return ResourceManager.GetString("ERR_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools, No Compared Data.
        /// </summary>
        internal static string ERR_20003 {
            get {
                return ResourceManager.GetString("ERR_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools, Compared Data Fail.
        /// </summary>
        internal static string ERR_20004 {
            get {
                return ResourceManager.GetString("ERR_20004", resourceCulture);
            }
        }
    }
}
